"""Where each number came from, and whether it still checks out."""

import pandas as pd
import streamlit as st

from dashboard import data


def render(run_id: int) -> None:
    st.caption(
        "Re-hashes each round's adapter on disk against what its messages "
        "recorded, and re-materialises the training pool to confirm it still "
        "hashes as it did. Generation is stochastic, so this — not a seed — is "
        "what makes a run checkable after the fact."
    )

    frame = data.provenance(run_id)
    if frame.empty:
        st.info("no rounds recorded yet")
        return

    failures = []
    for column in ("ckpt_ok", "pool_ok"):
        if column in frame:
            failures += list(frame[frame[column] == False]["round"])  # noqa: E712
    if failures:
        st.error(f"verification failed for round(s) {sorted(set(failures))}")
    else:
        st.success("every recorded round verifies")

    st.dataframe(frame, hide_index=True, use_container_width=True)
    st.caption(
        "`ckpt_stamps` is how many distinct adapters a round's messages point "
        "at — more than one means a round was generated by more than one "
        "checkpoint. `pool_hash` is the content hash of the exact rows that "
        "round trained on."
    )

    st.divider()
    st.subheader("Prompts")
    subjects = data.subjects_frame(run_id)
    st.caption(
        f"{len(subjects)} subjects, content-addressed and shared with every "
        "other run over the same prompts.json."
    )
    st.dataframe(subjects, hide_index=True, use_container_width=True)

    st.subheader("Decoding")
    frame = data.messages_frame(run_id)
    if not frame.empty and "decoding" in frame:
        distinct = {str(d) for d in frame["decoding"].dropna()}
        for spec in distinct:
            st.code(spec, language="python")
        if len(distinct) > 1:
            st.warning(
                "this run generated under more than one decoding spec — rounds "
                "are not comparable across the change"
            )
